# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

make_V <- function(x1, x10, x2) {
    .Call(`_did2s_make_V`, x1, x10, x2)
}

make_sandwich <- function(x2, meat_sum) {
    .Call(`_did2s_make_sandwich`, x2, meat_sum)
}

make_meat <- function(x2g, x10g, first_ug, second_ug, V) {
    .Call(`_did2s_make_meat`, x2g, x10g, first_ug, second_ug, V)
}

